global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'monitoring'
    scrape_interval: 5s
    static_configs:
      - targets: ['monitoring:9090']

  - job_name: 'linux'
    static_configs:
      - targets:
        - app:9100
        - cicd:9100
        - logging:9100
        - monitoring:9100
        - proxy:9100

  - job_name: 'postgres'
    static_configs:
      - targets:
        - app:9187
