deploy:
    container:
        db_password: ENC[AES256_GCM,data:u3Z7UAZTEz3F,iv:en0hQBgxv9F4mCc1nMKY+q7ngtNNQkEr6vo9U0UlnYA=,tag:4agFdwFn0HHRaHDeqTQYdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-27T12:36:42Z"
    mac: ENC[AES256_GCM,data:GeADEyIK4nLAKEzDNn63TD4HXkZLhL5jniMkqqPSl0zUC/wBMEmjlLv6TI9SPquoODN4L6r2PCgJpL9S1QadsjDhK3FbXZK8dqzzNW8nIKdOt5DhutmbkSHQS3kCIo6QyxSCKkOMvAtrVukb3B9Sh49sgyec/Sbx46zM9QBHkP0=,iv:O5HqbU21lYUE/+zg4DiEFqBXjJXeOj6ne1N4RmxlZ4g=,tag:/1kUdckE9XRxlVSDV0GpPQ==,type:str]
    pgp:
        - created_at: "2022-07-27T12:36:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DNlhhEV/eFWwSAQdAwX13LeyITr6BlFrOzBBxtyxU8wj0TEanpjKMcROVk0ow
            hUwcY0YgWi9QWA1r5Gprau+jGKTf0vtklBLRK5YI7Gzh4iFc7AnXOSxEpXYsQ4J0
            1GgBCQIQ/YFpRQ6mX6vEgQn1kE4iFfNbdnTOy7DK7lno2P6GoTRfhSR80gSlltYd
            6P/eNMsCAZNzhQd0IaI7AP5zZCvpKyaWniNBJNMD2ShHdum5yLeXQcbK93lTp4TX
            /rk8KBKJusKMBg==
            =gTtL
            -----END PGP MESSAGE-----
          fp: EC9BB3F6FB337BF2918B03977B6A27B90860D0FF
    unencrypted_suffix: _unencrypted
    version: 3.7.3
