pvc:
  name: wordpress-data
  storageclass: nfs-client
  storage: 300Mi

deploy:
  replicaCount: 1
  name: wordpress-dp
  label: wordpress
  container:
    name: wordpress
    image: wordpress:6.0.1-apache
    db_host: mysql-svc.mysql
    db_user: root
    db_password: 12345678
    db_name: wordpress
  volume:
    name: wordpress-volume
